env:
  global:
    # Package name
    - PACKAGE="Rainmeter"

language: python
python:
  - "3.3"

before_install:
  - curl -OL https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/travis.sh
  # enable gui, see https://docs.travis-ci.com/user/gui-and-headless-browsers
  - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

# command to install dependencie
install:
  # bootstrap the testing environment
  - sh travis.sh bootstrap
  # install Package Control and package denepdencies
  - sh travis.sh install_package_control

# command to run tests
script: 
  # run tests with test coverage report
  - sh travis.sh run_tests --coverage
  # run tests without test coverage report
  # - sh travis.sh run_tests
  # testing syntax_test files
  # - sh travis.sh run_syntax_tests

after_success:
  # remove the following if `coveralls` is not needed
  - if [ "$SUBLIME_TEXT_VERSION" == "3" ] && [ "$TRAVIS_OS_NAME" == "osx" ]; then
      brew update;
      brew install python3;
      pip3 install python-coveralls;
    fi
  - if [ "$SUBLIME_TEXT_VERSION" == "3" ] && [ "$TRAVIS_OS_NAME" == "linux" ]; then
      pip install python-coveralls;
    fi
  - if [ "$SUBLIME_TEXT_VERSION" == "3" ]; then
      coveralls;
    fi