environment:
    global:
        # The package name
        PACKAGE: "Rainmeter"
        SUBLIME_TEXT_VERSION : "3"

matrix:
    fast_finish: true
    allow_failures: 
        - platform: x86
        - platform: x64

# enable for debugging purposes
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    # install rainmeter
    # we do it by downloading the installer and install it in silent mode
    # TODO: silent mode is not supported anymore and automating with AutoIt failed
    # - ps: appveyor DownloadFile https://github.com/rainmeter/rainmeter/releases/download/v4.0.0.2722/Rainmeter-4.0-r2722-beta.exe -FileName C:/Rainmeter-setup.exe
    # - ps: C:/Rainmeter-setup.exe /S /D=C:/Program Files/Rainmeter /VERSION=64 /PORTABLE=0 /DESKTOPSHORTCUT=0 /STARTUP=0 /ALLUSERS=1

    # we download the special test environment for sublime text which can run commands from within the VM
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose

after_test:
    - ps: pip install coveralls

    # check if actually copied
    - ps: coverage report

    # set via AppVeyor environment token for privacy
    # or use encrypted versions and decrypt it here
    # - bat: set COVERALLS_REPO_TOKEN=XXXX
    # coveralls generally requires the .coverage file to be in the root folder
    # this is already copied for us from the "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" folder
    # - bat: copy "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" .coverage
    - coveralls

    # this needs to be here in after_test and not in on_success because artifacts are collected directly after after_test
    # package application without ps
    - gradlew.bat distribute

    # stop the daemon to cache gradle files later on
    - gradlew.bat --stop

artifacts:
    - path: build\Rainmeter.sublime-package

cache:
    - .gradle
    - '%userprofile%\.gradle'

# enable this to block the VM from closing
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))