environment:
    global:
        # The package name
        PACKAGE: "Rainmeter"
        SUBLIME_TEXT_VERSION : "3"

install:
    # Prepend newly installed Python to the PATH of this build (this cannot be
    # done from inside the powershell script as it would require to restart
    # the parent CMD process).
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose

after_test:
    - ps: pip install coveralls

    # check if actually copied
    - ps: coverage report

    # set via AppVeyor environment token for privacy
    # or use encrypted versions and decrypt it here
    # - bat: set COVERALLS_REPO_TOKEN=XXXX
    # coveralls generally requires the .coverage file to be in the root folder
    # this is already copied for us from the "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" folder
    # - bat: copy "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" .coverage
    - coveralls

    # this needs to be here in after_test and not in on_success because artifacts are collected directly after after_test
    # package application without ps
    - gradlew.bat distribute

    # stop the daemon to cache gradle files later on
    - gradlew.bat --stop

artifacts:
    - path: build\Rainmeter.sublime-package

cache:
    - .gradle
    - '%userprofile%\.gradle'
