environment:
    global:
        # The package name
        PACKAGE: "Rainmeter"
    matrix:
        - SUBLIME_TEXT_VERSION : "3"

install:
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    - ps: .\appveyor.ps1 "install_package_control" -verbose
    - ps: pip install python-coveralls

build: off

test_script:
    # - ps: .\appveyor.ps1 "run_tests" -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose
    - ps: python "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/run_tests.py" "--coverage" "$PACKAGE" 

after_test:
    - ps: coveralls 