environment:
    global:
        # The package name
        PACKAGE: "Rainmeter"
        SUBLIME_TEXT_VERSION : "3"

matrix:
    fast_finish: true
    allow_failures: 
        - platform: x86
        - platform: x64

# enable for debugging purposes
# init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    # install rainmeter
    # we use the github API to determine the latest rainmeter
    # we assume that the first entry is the latest
    # using the API and /releases/latest only results in releases and not pre-releases
    # rainmeter is typically offered as a pre-release

    # requests all releases from rainmeter                              | search for field bdu      | first entry| easier delimiter | 4th col without *        | pass url to curl -L to follow redirect
    - curl -s https://api.github.com/repos/rainmeter/rainmeter/releases | grep browser_download_url | head -n 1 | sed -e "s/""/*/g" | cut --delimiter="*" -f 4 | xargs curl -o C:\rainmeter-setup.exe -L

    # the project is installed into C:\projects\sublime-rainmeter via AppVeyor
    # the installer is located in the tests folder since this is used for integration testing
    # this will silently install rainmeter
    # we do not need to handle UAC since it is disabled in workers
    - C:\projects\sublime-rainmeter\tests\rainmeter-installer.exe
    
    # we download the special test environment for sublime text which can run commands from within the VM
    - ps: appveyor DownloadFile "https://raw.githubusercontent.com/randy3k/UnitTesting/master/sbin/appveyor.ps1"
    - ps: .\appveyor.ps1 "bootstrap" -verbose
    # install Package Control
    - ps: .\appveyor.ps1 "install_package_control" -verbose

build: off

test_script:
    - ps: .\appveyor.ps1 "run_tests" -coverage -verbose
    # testing syntax_test files
    # - ps: .\appveyor.ps1 "run_syntax_tests" -verbose

after_test:
    - ps: pip install coveralls

    # check if actually copied
    - ps: coverage report

    # set via AppVeyor environment token for privacy
    # or use encrypted versions and decrypt it here
    # - bat: set COVERALLS_REPO_TOKEN=XXXX
    # coveralls generally requires the .coverage file to be in the root folder
    # this is already copied for us from the "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" folder
    # - bat: copy "%appdata%\Roaming\Sublime Text 3\Packages\User\UnitTesting\Rainmeter\coverage" .coverage
    - coveralls

    # this needs to be here in after_test and not in on_success because artifacts are collected directly after after_test
    # package application without ps
    - gradlew.bat distribute

    # stop the daemon to cache gradle files later on
    - gradlew.bat --stop

artifacts:
    - path: build\Rainmeter.sublime-package

cache:
    - .gradle
    - '%userprofile%\.gradle'

# enable this to block the VM from closing
# on_finish:
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))